language: c
matrix:
        include:
                - os: linux
                  sudo: required
                  dist: bionic
                  install: ./.travis/install_deps.sh
                  script: ./.travis/compile.sh
